apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-tws
  namespace: three-tier
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/three-tier/db
