apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 3500
    targetPort: 3500
    protocol: TCP
    nodePort: 31002    
  type: ClusterIP
  selector:
    role: api
